const name = document.getElementById("name")
const password = document.getElementById("password")
const phone = document.getElementById("phone")
const email = document.getElementById("email")
const age = document.getElementById("age")